"""Phase 3 verification: chunk persistence, embedding cache, and a real
end-to-end answer generated by the local Ollama model.

Run:  .venv/bin/python test_phase3.py
"""

from __future__ import annotations

import os
import re
import sqlite3
import tempfile

from graph import GraphDB
from indexer import build_graph, GRAPH_DIR
from querier import answer_question, ollama_models, pick_model
from retriever import HybridRetriever

FIXTURE = {
    "auth.py": '''\
import hashlib
from db import get_user


def hash_password(password):
    """Return the sha256 hex digest of a password."""
    return hashlib.sha256(password.encode()).hexdigest()


def verify_login(username, password):
    """Check a username / password pair against the stored user record."""
    user = get_user(username)
    if user is None:
        return False
    return user["pw_hash"] == hash_password(password)
''',
    "db.py": '''\
_USERS = {}


def get_user(username):
    """Look up a user record by username."""
    return _USERS.get(username)
''',
    "api.py": '''\
from auth import verify_login


def login_endpoint(request):
    """HTTP handler: authenticate the incoming request."""
    ok = verify_login(request["user"], request["password"])
    return {"status": 200 if ok else 401}
''',
}

REPO_ID = "phase3_fixture"


def _index_fixture() -> str:
    root = tempfile.mkdtemp(prefix="phase3_src_")
    for name, body in FIXTURE.items():
        with open(os.path.join(root, name), "w") as fh:
            fh.write(body)
    os.makedirs(GRAPH_DIR, exist_ok=True)
    db_path = os.path.join(GRAPH_DIR, f"{REPO_ID}.sqlite")
    if os.path.exists(db_path):
        os.remove(db_path)
    build_graph(root, db_path)
    return db_path


def test_chunk_persistence_and_embedding_cache(db_path):
    conn = sqlite3.connect(db_path)
    n_chunks = conn.execute("SELECT COUNT(*) FROM chunks").fetchone()[0]
    n_embedded = conn.execute(
        "SELECT COUNT(*) FROM chunks WHERE embedding IS NOT NULL").fetchone()[0]
    conn.close()
    assert n_chunks >= 5, n_chunks
    assert n_embedded == 0, "embeddings should not exist before from_graph()"

    HybridRetriever.from_graph(db_path)  # side effect: caches embeddings

    conn = sqlite3.connect(db_path)
    n_embedded = conn.execute(
        "SELECT COUNT(*) FROM chunks WHERE embedding IS NOT NULL").fetchone()[0]
    conn.close()
    assert n_embedded == n_chunks, (n_embedded, n_chunks)
    print(f"  ok  {n_chunks} chunks persisted, {n_embedded} embeddings cached to SQLite")


def test_ollama_available():
    models = ollama_models()
    assert models, "Ollama returned no models - is `ollama serve` running?"
    chosen = pick_model()
    print(f"  ok  Ollama reachable; models={models}; will generate with '{chosen}'")
    return chosen


def test_end_to_end_answer():
    out = answer_question(REPO_ID, "How does password login verification work, "
                                   "and what does it call?")
    assert out["answer"] and len(out["answer"]) > 40, out["answer"]
    assert re.search(r"\[[\w./]+:\d+-\d+\]", out["answer"]), \
        f"answer has no [path:start-end] citation:\n{out['answer']}"

    cited_syms = {c["symbol_name"] for c in out["citations"]}
    assert "verify_login" in cited_syms, cited_syms

    g = out["graph"]
    roles = {n["role"] for n in g["nodes"]}
    labels = {n["label"] for n in g["nodes"]}
    assert "seed" in roles, roles
    assert {"verify_login", "get_user", "hash_password", "login_endpoint"} <= labels, labels

    # the visualiser renders the call path from these edges
    label_by_id = {n["id"]: n["label"] for n in g["nodes"]}
    edge_pairs = {(label_by_id[e["source"]], label_by_id[e["target"]], e["label"])
                  for e in g["edges"]}
    assert ("verify_login", "get_user", "CALLS") in edge_pairs, edge_pairs
    assert ("verify_login", "hash_password", "CALLS") in edge_pairs, edge_pairs
    assert ("login_endpoint", "verify_login", "CALLS") in edge_pairs, edge_pairs
    assert any(lbl == "IMPORTS" for _, _, lbl in edge_pairs), edge_pairs

    print(f"  ok  end-to-end answer generated by '{out['model']}'")
    print(f"        citations: {sorted(cited_syms)}")
    print(f"        graph: {len(g['nodes'])} nodes / {len(g['edges'])} edges")
    print(f"        call edges: {sorted(e for e in edge_pairs if e[2]=='CALLS')}")
    print("\n----- ANSWER -----")
    print(out["answer"])
    print("------------------")
    return out


def main():
    print("indexing fixture …")
    db_path = _index_fixture()

    failed = 0
    for fn in (lambda: test_chunk_persistence_and_embedding_cache(db_path),
               test_ollama_available,
               test_end_to_end_answer):
        try:
            fn()
        except AssertionError as exc:
            failed += 1
            print(f"  FAIL  {getattr(fn, '__name__', 'test')}: {exc}")
        except Exception as exc:  # noqa: BLE001
            failed += 1
            print(f"  ERROR {getattr(fn, '__name__', 'test')}: {exc!r}")

    print("\nPASS" if not failed else f"\n{failed} FAILED")
    raise SystemExit(1 if failed else 0)


if __name__ == "__main__":
    main()
